language: rust

rust:
- nightly

env:
- CARGO_INCREMENTAL=0

os: linux

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target

before_script:
- rustup component add rust-src
- "(test -x $HOME/.cargo/bin/xargo || cargo install xargo)"
- "(test -x $HOME/.cargo/bin/bootimage || cargo install bootimage)"
- "(test -x $HOME/.cargo/bin/cargo-xbuild || cargo install cargo-xbuild)"

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

script:
- bootimage build
