[package]
name = "nebulet"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]

[package.metadata.bootimage]
default-target = "x86_64-nebulet"
output = "bootimage.bin"

# We're pulling down the pre-compiled bootloader, so no
# need to build it. (Also avoids a bug in xargo)
#[package.metadata.bootimage.bootloader]
#git = "https://github.com/rust-osdev/bootloader.git"

[profile.release]
lto = true

[workspace]
members = ["tools"]
exclude = [
    "target/x86_64-nebulet/release/bootloader",
    "target/x86_64-nebulet/debug/bootloader",
    "cretonne"
]

[features]
default = ["dlmalloc_rs", "serial"]
vga = [] # log to vga
serial = [] # log to serial
bump_alloc = []
dlmalloc_rs = []
linked_alloc = ["linked_list_allocator"]

[dependencies]
spin = "0.4.6"
rlibc = "1.0.0"
bitflags = "1.0.1"
bit_field = "0.9.0"

x86_64 = "0.2.0-alpha-019"
os_bootinfo = "0.2.0"
hashmap_core = "0.1.5"

[dependencies.lazy_static]
version = "1.0.0"
features = ["spin_no_std"]

[dependencies.linked_list_allocator]
version = "0.5.0"
optional = true

[dependencies.nebulet_abi]
path = "nabi"

# Cretonne compiler
[dependencies.cretonne-codegen]
path = "cretonne/lib/codegen"
default-features = false
features = ["core"]

[dependencies.cretonne-frontend]
path = "cretonne/lib/frontend"
default-features = false
features = ["core"]

[dependencies.cretonne-wasm]
path = "cretonne/lib/wasm"
default-features = false
features = ["core"]

[dependencies.cretonne-native]
path = "cretonne/lib/native"
default-features = false
features = ["core"]

[dependencies.wasmparser]
version = "0.16.0"
default_features = false
features = ["core"]