[package]
name = "nebulet"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]

[package.metadata.bootimage]
default-target = "x86_64-nebulet"
output = "bootimage.bin"

[package.metadata.bootimage.bootloader]
version = "0.2.0-alpha-004"

# We're pulling down the pre-compiled bootloader, so no
# need to build it. (Also avoids a bug in xargo)
#[package.metadata.bootimage.bootloader]
#git = "https://github.com/rust-osdev/bootloader.git"

[workspace]
members = ["tools"]
exclude = [
    "target/x86_64-nebulet/release/bootloader",
    "target/x86_64-nebulet/debug/bootloader",
    "cretonne"
]

[features]
default = ["dlmalloc_rs", "vga"]
vga = [] # log to vga
serial = [] # log to serial
bump_alloc = []
dlmalloc_rs = []
linked_alloc = ["linked_list_allocator"]

[dependencies]
spin = "0.4.6"
rlibc = "1.0.0"
bitflags = "1.0.1"
bit_field = "0.9.0"

x86_64 = "0.2.0-alpha-019"
os_bootinfo = "0.2.0"


[dependencies.hashmap_core]
git = "https://github.com/nebulet/hashmap_core.git"

[dependencies.lazy_static]
version = "1.0.0"
features = ["spin_no_std"]

[dependencies.linked_list_allocator]
version = "0.5.0"
optional = true

[dependencies.nebulet_abi]
path = "nabi"

# Cretonne compiler
[dependencies.cretonne]
path = "cretonne/lib/cretonne"
default-features = false
features = ["no_std"]

[dependencies.cretonne-frontend]
path = "cretonne/lib/frontend"
default-features = false
features = ["no_std"]

[dependencies.cretonne-wasm]
path = "cretonne/lib/wasm"
default-features = false
features = ["no_std"]

[dependencies.cretonne-native]
path = "cretonne/lib/native"
default-features = false
features = ["no_std"]

[dependencies.wasmparser]
git = "https://github.com/nebulet/wasmparser.rs.git"
branch = "no_std"